### ISSUE TITLE
bug in rmlinesmovingwinc.m

### ISSUE THREAD

**Issue by awakenting** [brian-lau/Chronux#2]
Hello,
I recently found a bug in another EEG toolbox where the author told me that it propagated from the Chronux toolbox so I wanted to report it here as well. The bug is described in [this issue](https://github.com/VisLab/EEG-Clean-Tools/issues/8).

**Comment by brian-lau** [comment]
Thanks for pointing that out. 
https://github.com/VisLab/EEG-Clean-Tools/commit/0da237365cd873ef5e6bf174aab650385ebc04fa

**Comment by brian-lau** [comment]
Fixed in commit 15526c7f
